on:
  workflow_dispatch:
  push:
    branches:
    - production
    - preview

run-name: Build & deploy to ${{github.ref_name}}

concurrency:
  group: pages-${{github.ref_name}}
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write

env:
  stage: ${{github.ref_name}}
  preview_repo: NaukaPythona/preview.naukapythona.com
  build_ref: build/${{github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: getsentry/action-setup-venv@v2.1.0
      with:
        cache-dependency-path: requirements.lock
        install-cmd: pip install -r requirements.lock
    - run: mkdocs gh-deploy --strict --no-history --remote-branch ${{env.build_ref}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ${{github.ref_name}}
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{env.stage == 'preview' && env.preview_repo || github.repository}}
          ref: ${{env.build_ref}}
      - run: git fetch upstream && git push
        if: ${{env.stage == 'preview'}}
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@v4
