on:
  push:
    branches:
    - main

name: Production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: getsentry/action-setup-venv@v2.1.0
      with:
        cache-dependency-path: requirements.lock
        install-cmd: pip install -r requirements.lock
    - run: mkdocs gh-deploy --strict --no-history --remote-branch build/production
